# Generated by Django 6.0.6 on 2026-06-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(help_text="如 'changjian', 'jianan' 等硬编码ID", max_length=50, verbose_name='目标ID')),
                ('target_type', models.CharField(choices=[('weapon', '武器'), ('hero', '英雄')], max_length=20, verbose_name='目标类型')),
                ('category', models.CharField(choices=[('combo', '连招分享'), ('insight', '实战感悟')], default='insight', max_length=20, verbose_name='内容分类')),
                ('content', models.TextField(verbose_name='心得内容(Markdown)')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '玩家心得',
                'verbose_name_plural': '玩家心得',
                'db_table': 'user_contributions',
                'ordering': ['-created_at'],
            },
        ),
    ]
